---
services:

  jekyll:
    image: jekyll/jekyll
    platform: linux/amd64
    volumes:
      - .:/srv/jekyll:Z
    command: bash -c ' gem install webrick && jekyll serve --watch --force-polling'
    ports:
      - 4000:4000
