name: Check code style and quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"
      - name: install
        run: pnpm install
      - name: ESLint
        run: pnpm run lint
      - name: Prettier
        run: pnpm run prettier:check
      - name: Typescript
        run: pnpm run types
